### ISSUE TITLE
Please attach a license to this repository

### ISSUE THREAD

**Issue by avamk** [kjpluck/KeelingAndGlobalTemperature#1]
Amazing work on this visualisation!

Unfortunately no one can make us of, or even fork, this code without an appropriate license. I suggest the GPLv3+ which can be easily selected through this repository's settings. Thanks!

**Comment by kjpluck** [comment]
Thanks!
Done.

**Comment by avamk** [comment]
Awesome, thank you @kjpluck!! :D
